fix: update jar file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -2,9 +2,11 @@ name: CI/CD Pipeline
 
 on:
   push:
-    branches: [ "master" ]
+    branches:
+      - master
   pull_request:
-    branches: [ "master" ]
+    branches:
+      - master
 
 jobs:
   build-and-test:
@@ -52,15 +54,23 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # 3. Docker 이미지 빌드
+      # 3. JAR 파일 확인
+      - name: Verify JAR file exists
+        run: |
+          if [ ! -f "build/libs/auth-todo-0.0.1-SNAPSHOT.jar" ]; then
+            echo "JAR file not found! Exiting..."
+            exit 1
+          fi
+
+      # 4. Docker 이미지 빌드
       - name: Build Docker Image
         run: docker build -t syhere/auth-todo-app:latest .
 
-      # 4. Docker 이미지 푸시
+      # 5. Docker 이미지 푸시
       - name: Push Docker Image
         run: docker push syhere/auth-todo-app:latest
 
-      # 5. SSH를 통해 서버로 배포
+      # 6. AWS EC2에 배포
       - name: Deploy to AWS EC2
         uses: appleboy/ssh-action@v0.1.10
         with:
@@ -76,25 +86,3 @@ jobs:
               -e SPRING_DATASOURCE_USERNAME=admin \
               -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }} \
               syhere/auth-todo-app:latest
-
-  dependency-submission:
-    name: Dependency Submission
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-
-    steps:
-      # 1. 코드 체크아웃
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      # 2. Java 환경 설정
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-
-      # 3. 의존성 그래프 생성 및 제출
-      - name: Generate and submit dependency graph
-        uses: gradle/actions/dependency-submission@v4
